<?php

function autism_jma_service_listing_preprocess_field(&$variables) {
  if ($variables['entity_type'] == 'civicrm_contact' && $variables['field_name'] == 'organization_name') {
    $id = $variables['element']['#object']->id();
    $contactDetails = \civicrm_api3('Contact', 'get', ['id' => $id, 'return' => ['custom_897', 'custom_896']]);
    $modulePath = \Drupal::moduleHandler()->getModule('autism_jma_service_listing')->getPath();
    if ($variables['element']['#view_mode'] === 'search_teaser') {
      $size = '16px';
    }
    else {
      $size = '24px';
    }
    if (!empty($contactDetails['values'])) {
      if (!empty($contactDetails['values'][$contactDetails['id']]['custom_897'])) {
        $servicesProvided = $contactDetails['values'][$contactDetails['id']]['custom_897'];
        if (in_array(3, $servicesProvided)) {
          $variables['items'][0]['content']['#value'] .= ' <img src="'. file_create_url($modulePath . '/img/icon_local_travel_' . $size . '.png') . '" title="Travels to nearby areas">';
        }
        if (in_array(4, $servicesProvided)) {
          $variables['items'][0]['content']['#value'] .= ' <img src="'. file_create_url($modulePath . '/img/icon_remote_travel_' . $size . '.png') . '" title="Travels to remote areas">';
        }
      }
      if (isset($contactDetails['values'][$contactDetails['id']]['custom_896'])) {
        if (!empty($contactDetails['values'][$contactDetails['id']]['custom_896'])) {
          $variables['items'][0]['content']['#value'] .= ' <img src="'. file_create_url($modulePath . '/img/icon_accepting_' . $size . '.png') . '" title="Accepting new clients">';
        }
        else {
          $variables['items'][0]['content']['#value'] .= ' <img src="'. file_create_url($modulePath . '/img/icon_not_accepting_' . $size . '.png') . '" title="Not accepting new clients">';
        }
      }
    }
  }
}

function autism_jma_service_listing_login_user_login($account) {
  $current_route = \Drupal::routeMatch()->getRouteName();
  $destination = \Drupal::request()->query->get('destination');
  if ($destination && $destination != '/user/login') {
    return;
  }
  if (!in_array($current_route, ['user.reset', 'user.reset.login'])) {
    $current_user = \Drupal::currentUser();
    $roles = (array) $current_user->getRoles();
    if (in_array('authorized_contact', $roles)) {
      $response = new RedirectResponse(URL::fromUserInput('/civicrm/service-listing-application')->toString());
      $response->send();
    }
  }
}
