<?php
define('EVENT_IMAGE', 'custom_833');

use Drupal\Core\Language\LanguageInterface;
use Drupal\views\Plugin\views\cache\CachePluginBase;
use Drupal\views\Plugin\views\query\QueryPluginBase;
use Drupal\views\Plugin\views\PluginBase;
use Drupal\views\ViewExecutable;
use Drupal\Core\Form\FormStateInterface;
use Drupal\views\Views;
use Drupal\search_api\Entity\Index;

function jma_customizations_css_alter(&$css, \Drupal\Core\Asset\AttachedAssetsInterface $assets)
{
    $uri = \Drupal\Core\Url::fromRoute('<current>');
    $current_uri = $uri->getInternalPath();
    $paths = [
        "civicrm/contribute/transact",
        "civicrm/event/register",
        "civicrm/event/info",
        "civicrm-event",
        "civicrm/profile/view",
        "civicrm/profile/edit",
        "civicrm/profile/create",
        "civicrm/contact/map",
        "webform/civicrm_contact",
        "webform/civicrm_contact/confirmation",
        "civicrm/user",
        "civicrm/feedback",
        "civicrm/service-listing-application",
        "civicrm/service-listing-application-confirm",
        "civicrm/service-listing-thankyou",
        "civicrm/grant/transact",
        "civicrm/mailing/optout",
        "civicrm/mailing/unsubscribe",
    ];
    if (strpos($current_uri, 'civicrm') !== false && !in_array($current_uri, $paths)) {
        unset($css['themes/contrib/adminimal_theme/css/adminimal.css']);
        unset($css['themes/custom/de_theme/dist/css/de_theme.css']);
        unset($css['modules/contrib/adminimal_admin_toolbar/css/adminimal_admin_toolbar.css']);
    }
}

function jma_customizations_preprocess_views_view_field(&$variables) {
  $view = $variables['view'];
  $field = $variables['field'];
  $modulePath = \Drupal::moduleHandler()->getModule('jma_customizations')->getPath();
  if ($view->storage->id() == 'contact_map') {
    if ($field->field == 'display_name') {
      $variables['output'] = \Drupal\Core\Render\Markup::create(str_replace('Self-employed ', '', $variables['output']));
    }
  }
  if ($view->storage->id() == 'service_listing') {
    if ($field->field == 'display_name') {
      if (!empty($view->args[0])) {
        $content = $variables['output'];
        $contactDetails = \civicrm_api3('Contact', 'get', ['id' => $view->args[0], 'return' => ['custom_897', 'custom_896', 'custom_911', 'custom_895']]);
        if ((!empty($contactDetails['values'][$contactDetails['id']]['custom_911']) && !in_array('None', $contactDetails['values'][$contactDetails['id']]['custom_911'])) ||
          !empty($contactDetails['values'][$contactDetails['id']]['custom_895'])) {
          $content  = '<img src="'. file_create_url($modulePath . '/img/icon_verified_24px.svg') . '" title="' . t('Regulated / Credentialed clinician') . '"> ' . $content;
        }
      }
      $variables['output'] = \Drupal\Core\Render\Markup::create(str_replace('Self-employed ', '', $content));
    }
    if ($field->field == 'nothing') {
      if (!empty($view->args[0])) {
        $org = \civicrm_api3('Contact', 'get', ['id' => $view->args[0], 'sequential' => 1, 'return' => ['custom_897', 'custom_896', 'custom_911', 'custom_895']])['values'];
        $ABAcreds = \CRM_Utils_Array::value('custom_911', $org[0]);
        $ABAoptions = \CRM_Core_OptionGroup::values('aba_credentials_held_20200401123810');
        $regulatedServices = \CRM_Utils_Array::value('custom_895', $org[0]);
        $regulatedServicesOptions = \CRM_Core_OptionGroup::values('regulated_services_provided_20200226231106');
        if (empty($regulatedServices) && empty($ABAcreds)) {
          return;
        }
        $contactDetails = \civicrm_api3('Relationship', 'get', [
          'contact_id_b' => $view->args[0],
          'relationship_type_id' => 5,
          'is_active' => 1,
          'sequential' => 1,
          'api.Contact.get' => [
            'id' => "\$value.contact_id_a",
            'sequential' => 1,
            'return' => ['display_name', 'sort_name', 'custom_910', 'custom_953', 'custom_954'],
          ],
        ])['values'];
        $contacts = [];
        foreach ($contactDetails as $value) {
          if (!empty($value['api.Contact.get']['values'])) {
            foreach ($value['api.Contact.get']['values'] as $key => $employees) {
              if (!empty($contacts[$employees['sort_name']])) {
                continue;
              }
              $creds = [];
              if (!empty($employees['custom_953'])) {
                foreach ($employees['custom_953'] as $cred) {
                  if (!empty($ABAoptions[$cred])) {
                    $creds[] = $ABAoptions[$cred];
                  }
                }
              }
              if (!empty($employees['custom_954'])) {
                foreach  ($employees['custom_954'] as $cred) {
                  if (!empty($regulatedServicesOptions[$cred])) {
                    $creds[] = $regulatedServicesOptions[$cred];
                  }
                }
              }
              $creds =  implode(', ', $creds);
              $creds = $creds !== '' ? '(' . $creds . ')' : '';
              $verfiedIcon = $creds == '' ? '' : '<img src="'. file_create_url($modulePath . '/img/icon_verified_24px.svg') . '" title="' . t('Regulated / Credentialed clinician') . '"> ';
              $contacts[$employees['sort_name']] = sprintf('<div>%s %s %s</div>', $verfiedIcon, $employees['display_name'], $creds);
            }
          }
        }
        if (!empty($contacts)) {
          ksort($contacts);
          $contacts = "<div id='staff-section'>" . implode(' ', $contacts) . "</div>";
          $variables['output'] = \Drupal\Core\Render\Markup::create($variables['output'] . $contacts);
        }
      }
    }
    if ($field->field == 'contact_sub_type') {
      $title = $variables['output'];
      if (!empty($view->args[0])) {
        $contactDetails = \civicrm_api3('Contact', 'get', ['id' => $view->args[0], 'return' => ['custom_897', 'custom_896', 'custom_911', 'custom_895']]);
        if (!empty($contactDetails['values'])) {
          if (!empty($contactDetails['values'][$contactDetails['id']]['custom_897'])) {
            $servicesProvided = $contactDetails['values'][$contactDetails['id']]['custom_897'];
            if (in_array(2, $servicesProvided)) {
              $title .= ' <img src="'. file_create_url($modulePath . '/img/icon_videoconferencing_24px.png') . '" title="' . t('Online') . '">';
            }
            if (in_array(3, $servicesProvided)) {
              $title .= ' <img src="'. file_create_url($modulePath . '/img/icon_local_travel_24px.png') . '" title="' . t('Travels to nearby areas') . '">';
            }
            if (in_array(4, $servicesProvided)) {
              $title .= ' <img src="'. file_create_url($modulePath . '/img/icon_remote_travel_24px.png') . '" title="' . t('Travels to remote areas') . '">';
            }
          }
          if (isset($contactDetails['values'][$contactDetails['id']]['custom_896'])) {
            if (!empty($contactDetails['values'][$contactDetails['id']]['custom_896'])) {
              $title .= ' <img src="'. file_create_url($modulePath . '/img/icon_accepting_24px.png') . '" title="' . t('Accepting new clients') . '">';
            }
            else {
              $title .= ' <img src="'. file_create_url($modulePath . '/img/icon_not_accepting_24px.png') . '" title="' . t('Not accepting new clients') . '">';
            }
          }
        }
      }
      $variables['output'] = \Drupal\Core\Render\Markup::create($title);
    }
    if ($field->field == 'custom_911' || $field->field === 'custom_895' || $field->field === 'regulated_services_provided_863' || $field->field === 'aba_credentials_held_911') {
      if (!empty($variables['output']) && strpos($variables['output'], 'None of the above') === FALSE) {
        $parts = explode(',', $variables['output']);
        foreach ($parts as &$p) {
          $p = ' <img src="'. file_create_url($modulePath . '/img/icon_verified_16px.svg') . '" title="' . t('Regulated / Credentialed clinician') .  '"> ' . $p;
        }
        $variables['output'] = implode(',', $parts);
      }
      if ($field->field === 'custom_895' || $field->field === 'regulated_services_provided_863') {
        if (!empty($view->args)) {
          $serviceProviderEventses = \CRM_Core_DAO::executeQuery("SELECT a.id as `id`, a.camp_session_name_858 as `Camp_Session_Name`, a.from_859 as `From`, a.to_860 as `To`, a.entity_id as `entity_id`
            FROM civicrm_value_service_listi_72 a
            WHERE (`a`.`entity_id` = %1)", [1 => [$view->args[0], 'Positive']])->fetchAll();
          if (!empty($serviceProviderEventses)) {
            $variables['output'] .= '</span></div><div class="views-field views-field-event-camp"><h4>Camp Sessions</h4>';
            foreach ($serviceProviderEventses as $event) {
              $variables['output'] .= '<div class="views-field">' . $event['Camp_Session_Name'] . '<br>' . getCampDates($event['From'], $event['To']) . '</div>';
            }
            $variables['output'] .= '</div>';
          }
        }
      }
      $variables['output'] = \Drupal\Core\Render\Markup::create($variables['output']);
    }
    if ($field->field == 'custom_905' || $field->field == 'other_language_s__905') {
      $content = $variables['output'];
      $stateProvinceAbbreviations = \civicrm_api3('Address', 'getoptions', ['field' => 'state_province_id', 'context' => 'abbreviate'])['values'];
      $addresses = \civicrm_api3('Address', 'get', ['contact_id' => $view->args[0], 'options' => ['sort' => 'is_primary desc'], 'sequential' => 1]);
      $phones = \civicrm_api3('Phone', 'get', ['contact_id' => $view->args[0], 'options' => ['sort' => 'is_primary desc'], 'sequential' => 1]);
      if (!empty($addresses['values'])) {
        foreach ($addresses['values'] as $key => $details) {
          if ($key === 0) {
            $keyPlaceholder = \Drupal::config('geolocation_google_maps.settings')->get('google_map_api_key');
            $content .= '</span></div><script async defer src="https://maps.googleapis.com/maps/api/js?key=' . $keyPlaceholder . '"></script>';
          }
          $content .= '<div class="views-field views-field-address-details"><div class="left column" style="float:left; margin-right:20px; min-width: 210px;">';
          if ($key === 0) {
            if (\Drupal::languageManager()->getCurrentLanguage()->getId() == 'fr') {
              $content .= 'Lieu de travail principal';
            }
            else {
              $content .= 'Primary Work Location';
            }
          }
          else {
            if (\Drupal::languageManager()->getCurrentLanguage()->getId() == 'fr') {
              $content .= 'Lieu de travail complémentaire ' . $key;
            }
            else {
              $content .= 'Supplementary Work Location ' . $key;
            }
          }
          if (!empty($details['geo_code_1']) && !empty($details['geo_code_2'])) {
            $html = '<div id="address-map-%key%" onclick="window.location.href=\'/contact-map/' . $view->args[0] .'\'" data-lat="%lat%" data-lng="%long%" style="height: 100px; widgth: 100%;" data-maker-title="%street_address%"></div>';
            $html = str_replace('%key%', $key + 1, $html);
            $html = str_replace('%lat%', $details['geo_code_1'], $html);
            $html = str_replace('%long%', $details['geo_code_2'], $html);
            $html = str_replace('%street_address%', '<br>' . $details['street_address'] . '<br>' . $details['city'] . ', ' . $stateProvinceAbbreviations[$details['state_province_id']], $html);
            $content .= "<br /><br />" . $html;
          }

          $content .= '</div><div class="right column" style="min-height: 10em"><a href="tel:' . $phones['values'][$key]['phone'] . '">' . $phones['values'][$key]['phone'] . '</a>';
          $content .= '<br>' . $details['street_address'] . '<br>' . $details['city'] . ', ' . $stateProvinceAbbreviations[$details['state_province_id']];
          $content .= '<br>' . $details['postal_code'];
          $content .= '</div></div>';
        }
      }
      $variables['output'] = \Drupal\Core\Render\Markup::create(substr($content, 0, -6));
    }
  }
}

function jma_customizations_preprocess_field(&$variables) {
  if ($variables['entity_type'] == 'civicrm_contact' && $variables['field_name'] == 'organization_name') {
    $id = $variables['element']['#object']->id();
    $contactDetails = \civicrm_api3('Contact', 'get', ['id' => $id, 'return' => ['custom_897', 'custom_896', 'custom_911', 'custom_895']]);
    $modulePath = \Drupal::moduleHandler()->getModule('jma_customizations')->getPath();
    if ($variables['element']['#view_mode'] === 'search_teaser') {
      $size = '16px';
    }
    else {
      $size = '24px';
    }
    $variables['items'][0]['content']['#value'] = str_replace('Self-employed ', '', $variables['items'][0]['content']['#value']);
    if (\Drupal::languageManager()->getCurrentLanguage()->getId() == 'fr') {
      $variables['items'][0]['content']['#value'] = str_replace('/civicrm-contact', '/fr/civicrm-contact', $variables['items'][0]['content']['#value']);
    }
    if (!empty($contactDetails['values'])) {
      if (!empty($contactDetails['values'][$contactDetails['id']]['custom_897'])) {
        $servicesProvided = $contactDetails['values'][$contactDetails['id']]['custom_897'];
        if (in_array(2, $servicesProvided)) {
          $variables['items'][0]['content']['#value'] .= ' <img src="'. file_create_url($modulePath . '/img/icon_videoconferencing_' . $size . '.png') . '" title="' . t('Online') . '">';
        }
        if (in_array(3, $servicesProvided)) {
          $variables['items'][0]['content']['#value'] .= ' <img src="'. file_create_url($modulePath . '/img/icon_local_travel_' . $size . '.png') . '" title="' . t('Travels to nearby areas') . '">';
        }
        if (in_array(4, $servicesProvided)) {
          $variables['items'][0]['content']['#value'] .= ' <img src="'. file_create_url($modulePath . '/img/icon_remote_travel_' . $size . '.png') . '" title="' . t('Travels to remote areas') . '">';
        }
      }
      if (isset($contactDetails['values'][$contactDetails['id']]['custom_896'])) {
        if (!empty($contactDetails['values'][$contactDetails['id']]['custom_896'])) {
          $variables['items'][0]['content']['#value'] .= ' <img src="'. file_create_url($modulePath . '/img/icon_accepting_' . $size . '.png') . '" title="' . t('Accepting new clients') . '">';
        }
        else {
          $variables['items'][0]['content']['#value'] .= ' <img src="'. file_create_url($modulePath . '/img/icon_not_accepting_' . $size . '.png') . '" title="' . t('Not accepting new clients') . '">';
        }
      }
      if ($size === '16px' && ((!empty($contactDetails['values'][$contactDetails['id']]['custom_911']) && !in_array('None', $contactDetails['values'][$contactDetails['id']]['custom_911']))
        || !empty($contactDetails['values'][$contactDetails['id']]['custom_895']))) {
        $variables['items'][0]['content']['#value'] = '<img src="'. file_create_url($modulePath . '/img/icon_verified_24px.svg') . '" title="' . t('Regulated / Credentialed clinician') . '"> ' . $variables['items'][0]['content']['#value'];
      }
    }
  }
}

function jma_customizations_views_query_alter(ViewExecutable $view, QueryPluginBase $query) {
  if ($view->id() == 'events') {
    // Traverse through the 'where' part of the query.
    foreach ($query->where as &$condition_group) {
      foreach ($condition_group['conditions'] as &$condition) {
        // If this is the part of the query filtering on title, chang the
        // condition to filter on node ID.
        if ($condition['field'] == 'civicrm_event.title') {
          $condition['field'] = 'civicrm_event.title_en_US';
        }
        if ($condition['field'] == 'civicrm_event.description') {
          $condition['field'] = 'civicrm_event.description_en_US';
        }
        if ($condition['field'] == 'civicrm_value_event_chapter_28_civicrm_event.chapter_325') {
          $condition['value'][0] = "([[:cntrl:]]|^)" . $condition['value'][0] . "([[:cntrl:]]|$)";
          $condition['operator'] = 'REGEXP';
        }
      }
    }
  }
}

function jma_customizations_search_api_query_alter(\Drupal\search_api\Query\QueryInterface &$query) {
  if ($query->getIndex()->getServerInstance()->supportsFeature('search_api_facets')) {
    /** @var \Drupal\facets\FacetManager\DefaultFacetManager $facet_manager */
    $facet_manager = \Drupal::service('facets.manager');

    $search_id = $query->getSearchId();

    // If we find an attachment view query, we use the same query alter
    // as the page because they belong together.
    if (strpos($search_id, 'views_attachment:search_') === 0) {
      $search_id = 'search_api:views_page__search_solr___page_1';

      // Add the active filters.
      $facet_manager->alterQuery($query, $search_id);
    }
  }
}

function jma_customizations_module_implements_alter(&$implementations, $hook) {
  if ($hook == 'page_attachments' || $hook == 'page_attachments_alter') {

    // Move my_module_form_alter() to the end of the list.
    // \Drupal::moduleHandler()->getImplementations()
    // iterates through $implementations with a foreach loop which PHP iterates
    // in the order that the items were added, so to move an item to the end of
    // the array, we remove it and then add it.
    $group = $implementations['jma_customizations'];
    unset($implementations['jma_customizations']);
    $implementations['jma_customizations'] = $group;
  }
}

function jma_customizations_page_attachments(array &$page) {
    $uri = \Drupal\Core\Url::fromRoute('<current>');
    $current_uri = $uri->getInternalPath();
    $paths = [
        "civicrm/event/register",
        "civicrm/event/info",
    ];
    if (strpos($current_uri, 'civicrm') !== false && in_array($current_uri, $paths)) {
      $eventId = \Drupal::request()->query->get('id');
      if (!$eventId) {
        return;
      }
      $event = civicrm_api3('Event', 'get', ['id' => $eventId, 'return' => ["title", "summary", EVENT_IMAGE]])['values'];
      $ogTitle = array(
        '#tag' => 'meta',
        '#attributes' => array(
          'property' => 'og:title',
          'name' => 'title',
          'content' => $event[$eventId]['title'],
        ),
      );

      $page['#attached']['html_head'][] = [$ogTitle, 'ogTitle'];

      if (!empty($event[$eventId]['summary'])) {
        $ogDescription = array(
          '#tag' => 'meta',
          '#attributes' => array(
            'property' => 'og:description',
            'name' => 'description',
            'content' => $event[$eventId]['summary'],
          ),
        );

        $page['#attached']['html_head'][] = [$ogDescription, 'ogDescription'];
      }

      $ogUrl = array(
        '#tag' => 'meta',
        '#attributes' => array(
          'property' => 'og:url',
          'name' => 'canonical_url',
          'content' => \Drupal::request()->getSchemeAndHttpHost() . \Drupal::request()->getRequestUri(),
        ),
      );

      $page['#attached']['html_head'][] = [$ogUrl, 'ogUrl'];

      if (!empty($event[$eventId][EVENT_IMAGE])) {
        // Fetch the image from database.
        $imageUri = CRM_Core_DAO::singleValueQuery("SELECT uri FROM civicrm_file WHERE id = %1", [1 => [$event[$eventId][EVENT_IMAGE], 'Integer']]);
        $ogImage = array(
          '#tag' => 'meta',
          '#attributes' => array(
            'property' => 'og:image',
            'name' => 'image',
            'content' => \Drupal::request()->getSchemeAndHttpHost() . '/sites/default/files/civicrm/custom/' . $imageUri,
          ),
        );

        $page['#attached']['html_head'][] = [$ogImage, 'ogImage'];
      }

      $ogType = array(
        '#tag' => 'meta',
        '#attributes' => array(
          'property' => 'og:type',
          'name' => 'type',
          'content' => 'article',
        ),
      );

     $page['#attached']['html_head'][] = [$ogType, 'ogType'];
  }
  if (strpos($current_uri, 'service-listing') !== FALSE && strpos($current_uri, 'service-listing-application') === FALSE && strpos($current_uri, 'service-listing-thankyou') === FALSE) {
    $parts = explode('/', $current_uri);
    \Drupal::service('civicrm')->initialize();
    $contactDetails = \civicrm_api3('Contact', 'get', ['id' => $parts[1]]);
    if (!empty($contactDetails['values'])) {
      $displayName = $contactDetails['values'][$contactDetails['id']]['display_name'];
      foreach ($page['#attached']['html_head'] as $key => $tagDetails) {
        if ($tagDetails[1] === 'title') {
          $content = str_replace('Self-employed ', '', $displayName) . ' ' . $tagDetails[0]['#attributes']['content'];
          $page['#attached']['html_head'][$key][0]['#attributes']['content'] = $content;
        }
      }
    }
  }
}

function jma_customizations_page_attachments_alter(array &$attachments) {
  $uri = \Drupal\Core\Url::fromRoute('<current>');
  $current_uri = $uri->getInternalPath();
  $paths = [
    "civicrm/event/register",
    "civicrm/event/info",
  ];
  if (strpos($current_uri, 'civicrm') !== false && in_array($current_uri, $paths)) {
    $invalidMetas = [
      'title',
      'description',
    ];
    foreach ($attachments['#attached']['html_head'] as $key => $attachment) {
      if (in_array($attachment[1], $invalidMetas)) {
        unset($attachments['#attached']['html_head'][$key]);
      }
    }
  }
}

function jma_customizations_preprocess_html(&$variables) {
  $variables['service_title'] = FALSE;
  $uri = \Drupal\Core\Url::fromRoute('<current>');
  $current_uri = $uri->getInternalPath();
  if (strpos($current_uri, 'service-listing') !== FALSE && strpos($current_uri, 'service-listing-application') === FALSE && strpos($current_uri, 'service-listing-thankyou') === FALSE) {
    $parts = explode('/', $current_uri);
    \Drupal::service('civicrm')->initialize();
    $contactDetails = \civicrm_api3('Contact', 'get', ['id' => $parts[1]]);
    if (!empty($contactDetails['values'])) {
      $variables['service_title'] = str_replace('Self-employed ', '', $contactDetails['values'][$contactDetails['id']]['display_name']) . ' ';
    }
  }
}

function jma_customizations_form_alter(&$form, \Drupal\Core\Form\FormStateInterface $form_state, $form_id) {
  if ($form_id === "views_exposed_form" && $form['#id'] == "views-exposed-form-events-page-1") {
    $anyText = '- Any - ';
    $fundRaisingText = 'Fundraising';
    if (\Drupal::languageManager()->getCurrentLanguage()->getId() == 'fr') {
      $anyText = '- Tous -';
      $fundRaisingText = 'Collecte de fonds';
    }
    $options = [
      'All' => $anyText,
    ];
    $eventTypes = CRM_Core_DAO::executeQuery("SELECT v.value, v.label AS label, v.name AS name
      FROM civicrm_event e
      INNER JOIN civicrm_option_value v ON v.value = e.event_type_id
      INNER JOIN civicrm_option_group g ON g.id = v.option_group_id
      WHERE e.id IN (SELECT id FROM civicrm_event WHERE DATE_FORMAT(end_date, '%Y-%m-%d') >= CURRENT_DATE() AND is_active = 1)
      AND g.name = 'event_type' GROUP BY v.value ORDER BY v.label")->fetchAll();
    foreach ($eventTypes as $eventType) {
      if ($eventType['name'] == "Fundraising with multi pax event") {
        $eventType['label'] = $fundRaisingText;
      }
      $options[$eventType['value']] = $eventType['label'];
    }
    $form['event_type_id']['#options'] = $options;
  }
  if ($form_id === "views_exposed_form" && $form['#id'] == "views-exposed-form-search-solr--page-1") {
    $form['#validate'][] = 'solr_address_geocoder';
    $form['#validate'][] = 'validate_camp_date_filter';
    $form['#attached']['library'][] = 'jma_customizations/advanced_search';
  }
}

function jma_customizations_views_pre_render(ViewExecutable $view) {
  if ($view->id() == 'event_map') {
    $view->element['#attached']['library'][] = 'jma_customizations/jma_customizations';
    $results = $view->result;
    // Find a better way to do this, for now, using a sample event.
    $event_ent = \Drupal::entityTypeManager()->getStorage('civicrm_event')->load(1327);
    foreach ($results as $i => &$row) {
      if (!empty($row->_entity)) {
        // Event is loaded here.
        // TODO: Derive the base URL
        $viewLink = "<a href='https://jma.staging.autismontario.com/civicrm/event/info?reset=1&id=" . $row->_entity->get('id')->value . "' target='_blank'>View event</a>";
        $row->_entity->set('id', $viewLink);
      }
      else {
        // Contact is loaded here.
        $contact_ent = \Drupal::entityTypeManager()->getStorage('civicrm_contact')->load($row->id);
        $row->_entity = $event_ent;
        $row->_entity->set('title', $contact_ent->get('display_name')->value);
        // TODO: Derive the base URL
        $viewLink = "<a href='https://jma.staging.autismontario.com/civicrm/contact/view?reset=1&cid=" . $row->id . "' target='_blank'>View service listing</a>";
        $row->_entity->set('id', $viewLink);
      }
    }
    $view->result = $results;
  }
  if ($view->id() == 'event_location') {
    foreach ($view->result as $k => $row) {
      if ($row->_entity) {
        $loc_block_id = $row->_entity->toArray()['loc_block_id'];
        if (!empty($loc_block_id[0]['target_id'])) {
          $sql = "SELECT CONCAT(street_address, ',', city, ',', postal_code, ',', 'Ontario') FROM civicrm_address a INNER JOIN civicrm_loc_block lb ON lb.address_id = a.id WHERE lb.id = " . $loc_block_id[0]['target_id'];
          $view->result[$k]->_entity->set('summary', str_replace(',', "\n", \CRM_Core_DAO::singleValueQuery($sql)));
        }
      }
      else {
        $id = $row->id;
        $contact_ent = \Drupal::entityTypeManager()->getStorage('civicrm_contact')->load($id);
        if (!empty($view->result[0]->_entity)) {
          $row->_entity = clone $view->result[0]->_entity;
        }
        else {
          $row->_entity = \Drupal::entityTypeManager()->getStorage('civicrm_event')->load(11);
        }
        $addresses = civicrm_api3('Address', 'get', ['sequential' => 1, 'contact_id' => $id])['values'];
        $params = [];
        $fulladdress = NULL;
        foreach ($addresses as $k => $address) {
          $address = (object) $address;
          $fulladdress = sprintf("\n %s \n %s \n %s \n Ontario", $address->street_address, $address->city, $address->postal_code);
          $address_id = $address->id;
          $params[$k] = [
           'lat' => $address->geo_code_1,
           'lng'=> $address->geo_code_2,
           'lat_sin' => sin(deg2rad($address->geo_code_1)),
           'lat_cos' => cos(deg2rad($address->geo_code_1)),
           'lng_rad' => deg2rad($address->geo_code_2),
         ];
         $params[$k]['data'] = $params[$k];
        }
        $row->_entity->set('id', $id);
        $row->_entity->set('title', str_replace('Self-employed', '', $contact_ent->get('display_name')->value));
        $row->_entity->set('summary', $fulladdress);
        $row->_entity->set('field_geolocation', $params);
      }
    }
  }
  if ($view->id() == 'search_solr_' || $view->id() == 'service_listing') {
    $view->element['#attached']['library'][] = 'jma_customizations/jma_customizations';
    $view->element['#attached']['library'][] = 'jma_customizations/service_listing';
    $view->element['#attached']['library'][] = 'jma_customizations/search_facet';
    if ($view->id() == 'search_solr_') {
      $search_api_facets = $view->query->getSearchApiResults()->getExtraData('search_api_facets', []);
      $facet_manager = \Drupal::service('facets.manager');
      $facet_storage = \Drupal::entityTypeManager()->getStorage('facets_facet');
      $facet = $facet_storage->load('type');
      $processed = $facet_manager->returnProcessedFacet($facet);
      $items = $facet_manager->build($processed);
      $showServiceListingLegend = TRUE;
      // if we have no type facet or Service Listing does not exist in the facet OR it does but is not an active item if there are any then we hide the lengend
      if (empty($search_api_facets['type'])) {
        $showServiceListingLegend = FALSE;
      }
      else {
        if (!empty($processed->getActiveItems()) && !$processed->isActiveValue('Service Listing')) {
          $showServiceListingLegend = FALSE;
        }
        if (array_search('"Service Listing"', array_column($search_api_facets['type'], 'filter')) === FALSE) {
          $showServiceListingLegend = FALSE;
        }
      }
      if (!$showServiceListingLegend) {
        $view->element['#attached']['library'][] = 'jma_customizations/service_listing_legend';
      }
    }
  }
}

/**
 * Implements hook_views_pre_execute().
 */
function jma_customizations_views_pre_execute(ViewExecutable $view) {
  if ($view->id() == 'event_location') {
    $query = &$view->build_info['query'];
    $ids = explode(' ', $view->args[0]);
    foreach ($ids as $k => $id) {
      if (strstr($id, 'contact')) {
        $ids[$k] = str_replace('contact', '', $id);
      }
      else {
        unset($ids[$k]);
      }
    }
    $ids = empty($ids) ? [] : $ids;
    if (!empty($ids)) {
       $query2 = \Drupal::database()->select('{civicrm_contact}', 'civicrm_contact');
       $query2->addField('civicrm_contact', 'id', 'id');
       $query2->innerJoin('civicrm_contact__field_geolocation', 'civicrm_contact__field_geolocation', 'civicrm_contact.id = civicrm_contact__field_geolocation.entity_id');
       $query2->condition('civicrm_contact.id', $ids, 'IN');
       $query = $query->union($query2);
       $view->build_info['query'] = $query;
     }
  }
  if ($view->id() == 'event_map') {
    $view2 = Views::getView('contact_map');
    $view2->build('page_1');
    $other_query = $view2->build_info['query'];

    $other_query->addField('civicrm_contact__field_geolocation', 'field_geolocation_lat_sin', 'field_geolocation_lat_sin');
    $other_query->addField('civicrm_contact__field_geolocation', 'field_geolocation_lat_cos', 'field_geolocation_lat_cos');
    $other_query->addField('civicrm_contact__field_geolocation', 'field_geolocation_lng_rad', 'field_geolocation_lng_rad');

    $view->build_info['query']->addField('civicrm_event__field_geolocation', 'field_geolocation_lat_sin', 'field_geolocation_lat_sin');
    $view->build_info['query']->addField('civicrm_event__field_geolocation', 'field_geolocation_lat_cos', 'field_geolocation_lat_cos');
    $view->build_info['query']->addField('civicrm_event__field_geolocation', 'field_geolocation_lng_rad', 'field_geolocation_lng_rad');
    $view->build_info['query']->union($other_query);

    $query = db_select($view->build_info['query'], 'location')->fields('location');

    if (!empty($view->exposed_data['lat'])) {
      $lat = $view->exposed_data['lat'];
    }
    if (!empty($view->exposed_data['lng'])) {
      $lng = $view->exposed_data['lng'];
    }
    $distance = 16.09344; // 10 Km
    if (!empty($view->exposed_data['field_geolocation_proximity'])) {
      $distance = $view->exposed_data['field_geolocation_proximity'];
    }
    $query = db_select($view->build_info['query'], 'location')->fields('location');

    $view->build_info['query'] = $query;
    if (!empty($lat) && !empty($lng)) {
      $fragment = ProximityTrait::getProximityQueryFragment('location', 'field_geolocation', $lat, $lng);
      $fragment .= " <= :distance";
      $view->build_info['query']->where($fragment, [':distance' => $distance]);
    }
  }
}

/**
 * @param \Drupal\user\UserInterface $user
 *
 * Implements hook_ENTITY_TYPE_insert() for user entities.
 */
function jma_customizations_user_insert(\Drupal\user\UserInterface $user) {
  $userId = $user->id();
  $cid = CRM_Core_DAO::singleValueQuery("SELECT contact_id FROM civicrm_uf_match WHERE uf_id = %1", [1 => [$userId, "Integer"]]);
  if (!empty($cid)) {
    // Check if this is a primary contact.
    $authorizedContact = civicrm_api3('Contact', 'get', [
      'id' => $cid,
      'contact_sub_type' => "authorized_contact",
    ]);
    if (!empty($authorizedContact['count']) && $authorizedContact['count'] == 1) {
      // The current contact is a primary contact.
      // Check roles to see if this is already an authorized contact.
      $roles = (array) $user->getRoles();
      if (!in_array('authorized_contact', $roles)) {
        $roles = array_merge($roles, ['authorized_contact']);
        $user->set('roles', array_unique($roles));
        $user->save();
      }
    }
  }
}

function jma_customizations_form_user_form_alter(&$form, \Drupal\Core\Form\FormStateInterface $form_state, $form_id) {
  $current_user = \Drupal::currentUser();
  $roles = (array) $current_user->getRoles();
  if (in_array('authorized_contact', $roles)) {
    foreach (array_keys($form['actions']) as $action) {
      if (isset($form['actions'][$action]['#type']) && $form['actions'][$action]['#type'] === 'submit') {
        $form['actions'][$action]['#submit'][] = '_jma_redirect_form_submit';
      }
    }
  }
}

function _jma_redirect_form_submit(array $form, FormStateInterface $form_state){
  $response = new Symfony\Component\HttpFoundation\RedirectResponse(\Drupal\Core\URL::fromUserInput('/civicrm/service-listing-application')->toString());
  $response->send();
}

function getCampDates($from, $to) {
  $content = 'From: ' . date('l, F j Y', strtotime($from)) . ' To: ' . date('l, F j Y', strtotime($to));
  if (\Drupal::languageManager()->getCurrentLanguage()->getId() == 'fr') {
    $english_days = array('Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday', 'Sunday');
    $french_days = array('lundi', 'mardi', 'mercredi', 'jeudi', 'vendredi', 'samedi', 'dimanche');
    $english_months = array('January', 'February', 'March', 'April', 'May', 'June', 'July', 'August', 'September', 'October', 'November', 'December');
    $french_months = array('janvier', 'février', 'mars', 'avril', 'mai', 'juin', 'juillet', 'août', 'septembre', 'octobre', 'novembre', 'décembre');
    $content = str_replace($english_months, $french_months, str_replace($english_days, $french_days, $content));
  }
  return $content;
}

function jma_customizations_views_data_alter(&$data) {
  /** @var \Drupal\search_api\IndexInterface $index */
  foreach (Index::loadMultiple() as $index) {
    $table = &$data['search_api_index_' . $index->id()];

    /** @var \Drupal\search_api\Item\FieldInterface $field */
    foreach ($index->getFields(TRUE) as $field_id => $field) {
      $field_alias = _search_api_location_views_get_field_alias($field_id, $table);
      if ($field->getType() == 'location') {
        $field_alias_proximity = $field_alias . '_proximity';
        // Add boundary handlers.
        $table[$field_alias_proximity] = [
          'group' => $field->getLabel(),
          'title' => t('Proximity (@field_name)', ['@field_name' => $field_alias]),
          'help' => $field->getDescription(),
          'filter' => [
            'id' => 'geolocation_proximity_views_filter',
            'allow empty' => TRUE,
            'real field' => $field_alias,
          ],
        ];
      }
      if ($field_id == 'custom_899') {
        $table[$field_alias]['filter'] = [
          'id' => 'lang_views_filter',
          'allow empty' => TRUE,
          'real field' => $field_alias,
        ];
      }
      elseif ($field_id == 'custom_898') {
        $table[$field_alias]['filter'] = [
          'id' => 'age_group_served_views_filter',
          'allow empty' => TRUE,
          'real field' => $field_alias,
        ];
      }
      elseif ($field_id == 'custom_897') {
        $table[$field_alias]['filter'] = [
          'id' => 'services_provided_views_filter',
          'allow empty' => TRUE,
          'real field' => $field_alias,
        ];
      }
      elseif ($field_id == 'custom_896') {
        $table[$field_alias]['filter'] = [
          'id' => 'accepting_client_views_filter',
          'allow empty' => TRUE,
          'real field' => $field_alias,
        ];
      }
    }
  }
}

function validate_camp_date_filter($form, FormStateInterface $form_state) {
  $values = $form_state->getValues();
  if (!empty($values['custom_891']) && !empty($values['custom_892']) && strncmp($values['custom_891'], $values['custom_892'], 10) > 0) {
    $form_state->setErrorByName('custom_891', t('\'From\' date should be greater or equal to \'To\' date'));
  }
}

function solr_address_geocoder($form, FormStateInterface $form_state) {
  $address = [];
  $values = $form_state->getValues();

  if (!empty($values['field_geolocation_2_proximity']['postal_code'])) {
    if (!preg_match("/^[A-Z][0-9][A-Z][\s]*[0-9][A-Z][0-9]$/i", $values['field_geolocation_2_proximity']['postal_code'])) {
      $form_state->setErrorByName('field_geolocation_2_proximity[postal_code]', t('Postal code format is not valid.'));
      return;
    }
    elseif (!preg_match("/^[ABCEGHJKLMNPRSTVXY][0-9][A-Z][\s]*[0-9][A-Z][0-9]$/i", $values['field_geolocation_2_proximity']['postal_code'])) {
      $form_state->setErrorByName('field_geolocation_2_proximity[postal_code]', t('Please specify a valid Canadian postal code'));
      return;
    }
  }
  foreach (['street_address', 'city', 'postal_code'] as $key) {
    if (!empty($values['field_geolocation_2_proximity'][$key])) {
      $address[] = $values['field_geolocation_2_proximity'][$key];
    }
  }
  // Limit to Ontario Canada only when other address field information is supplied
  if (!empty($address)) {
    $address[] = 'ON';
    $address[] = 'CA';
  }
  $address = implode(',', $address);
  if (!empty($address)) {
    $result = geocode($address);
    if (!$result || $result['status'] != 'OK') {
      $form_state->setErrorByName('field_geolocation_2_proximity[street_address]', t('The address for proximity search was not found'));
      $form_state->setValue(['field_geolocation_2_proximity', 'center_lat'], NULL);
      $form_state->setValue(['field_geolocation_2_proximity', 'center_long'], NULL);
    }
    elseif (!empty($result['results'][0]['geometry']['location'])) {
      $form_state->setValue(['field_geolocation_2_proximity', 'center_lat'], $result['results'][0]['geometry']['location']['lat']);
      $form_state->setValue(['field_geolocation_2_proximity', 'center_long'], $result['results'][0]['geometry']['location']['lng']);
    }
    else {
      $form_state->setValue(['field_geolocation_2_proximity', 'center_lat'], NULL);
      $form_state->setValue(['field_geolocation_2_proximity', 'center_long'], NULL);
    }
  }
  elseif (empty($values['field_geolocation_2_proximity']['current_location'])) {
    // We don't have address or current_location so set center_lat and center_long to null in case they are set.
    $form_state->setValue(['field_geolocation_2_proximity', 'center_lat'], NULL);
    $form_state->setValue(['field_geolocation_2_proximity', 'center_long'], NULL);
  }
}

function geocode($address) {
  $config = \Drupal::config('geolocation_google_maps.settings');
  if (empty($address)) {
    return FALSE;
  }

  if (!empty($config->get('google_maps_base_url'))) {
    $request_url = $config->get('google_maps_base_url');
  }
  else {
    $request_url = \Drupal\geolocation_google_maps\GoogleMapsProviderBase::$googleMapsApiUrlBase;
  }
  $request_url .= '/maps/api/geocode/json?address=' . urlencode($address);

  if (!empty($config->get('google_map_api_server_key'))) {
    $request_url .= '&key=' . $config->get('google_map_api_server_key');
  }
  elseif (!empty($config->get('google_map_api_key'))) {
    $request_url .= '&key=' . $config->get('google_map_api_key');
  }

  if (!empty($config->get('google_map_custom_url_parameters')['language'])) {
    $request_url .= '&language=' . $config->get('google_map_custom_url_parameters')['language'];
  }

  try {
    $result = \Drupal\Component\Serialization\Json::decode(\Drupal::httpClient()->request('GET', $request_url)->getBody());
  }
  catch (\GuzzleHttp\Exception\RequestException $e) {
    watchdog_exception('geolocation', $e);
    return FALSE;
  }

  if ($result['status'] != 'OK' || empty($result['results'][0]['geometry'])) {
    if (isset($result['error_message'])) {
      \Drupal::logger('geolocation')->error(t('Unable to reverse geocode "@latitude, $longitude" with error: "@error". Request URL: @url', [
        '@latitude' => $latitude,
        '@$longitude' => $longitude,
        '@error' => $result['error_message'],
        '@url' => $request_url,
      ]));
    }
  }

  return $result;
}

function jma_customizations_civicrm_alter_drupal_entities(&$supportedEntities) {
  $supportedEntities['civicrm_contact']['permissions']['view'] =
    $supportedEntities['civicrm_address']['permissions']['view'] =
      $supportedEntities['civicrm_email']['permissions']['view'] =
        $supportedEntities['civicrm_website']['permissions']['view'] =
          $supportedEntities['civicrm_phone']['permissions']['view'] =
           $supportedEntities['civicrm_relationship']['permissions']['view'] =  ['view event info'];
}
